--- 
redirects: 
  api/overview: ./library/api.md
  api/project: ./library/api.md
  api/run: ./library/api.md
  frameworks/keras: ./library/frameworks/keras.md
  getting-started: ./quickstart.md
  overview/company-faq: ./overview/company-faq.md
  overview/getting-help: ./overview/getting-help.md
  overview/overview: ./overview.md
  overview/technical-faq: ./overview/technical-faq.md
  wandb/config: ./library/python/config.md
  wandb/init: ./library/python/init.md
  wandb/log: ./library/python/log.md
  wandb/restore: ./library/python/restore.md
  wandb/save: ./library/python/save.md