--- 
redirects: 
  advanced/automated: ./library/advanced/environment-variables.md
  advanced/grouping: ./library/advanced/grouping.md
  advanced/limits: ./library/advanced/limits.md
  advanced/resuming: ./library/advanced/resuming.md
  advanced/security: ./library/advanced/security.md
  alerts/slack: ./app/features/alerts.md
  api/*: ./library/api.md
  "api/overview": ./quickstart.md
  "api/project": ./quickstart.md
  "api/run": ./quickstart.md
  cli/overview: ./library/cli.md
  cli/restoring: ./library/cli.md
  docs/: ./
  "docs/log#summary-metrics": ./library/python/log#summary-metrics.md
  docs/integrations/jupyter: ./library/integrations/jupyter.md
  docs/config: ./library/python/config.md
  docs/init: ./library/python/init.md
  docs/log: ./library/python/log.md
  docs/save: ./library/python/save.md
  docs/restore: ./library/python/restore.md
  enterprise/about: ./enterprise/overview.md
  enterprise/cloud/about: ./enterprise/cloud.md
  enterprise/server/about: ./enterprise/overview.md
  enterprise/server/config: ./enterprise/server/configuration.md
  enterprise/server/setup: ./enterprise/overview.md
  enterprise/server/upgrades: ./enterprise/server/upgrades.md
  enterprise/usage/sending-data: ./enterprise/sending-data.md
  frameworks/catalyst: ./library/integrations/catalyst.md
  frameworks/examples: ./library/example-projects.md
  frameworks/fastai: ./library/frameworks/fastai.md
  frameworks/fastai-example: ./library/example-projects/fastai.md
  frameworks/jax-example: ./library/example-projects/jax.md
  frameworks/keras: ./library/frameworks/keras.md
  frameworks/keras-example: ./library/example-projects/keras.md
  frameworks/numpy-example: ./library/example-projects/numpy.md
  frameworks/pytorch: ./library/frameworks/pytorch.md
  frameworks/pytorch-example: ./library/example-projects/pytorch.md
  frameworks/scikit: ./library/frameworks/scikit.md
  frameworks/scikit-example: ./library/example-projects/scikit.md
  frameworks/tensorflow: ./library/frameworks/tensorflow.md
  frameworks/tensorflow-example: ./library/example-projects/tensorflow.md
  frameworks/xgboost: ./library/frameworks/xgboost.md
  frameworks/xgboost-example: ./library/example-projects/xgboost.md
  getting-started: ./quickstart.md
  "integrations/api": ./library/api.md
  "integrations/api#special-methods": ./quickstart.md
  integrations/databricks: ./library/integrations/databricks.md
  integrations/docker: ./library/integrations/docker.md
  integrations/jupyter: ./library/integrations/jupyter.md
  integrations/kubeflow: ./library/integrations/kubeflow.md
  integrations/ray: ./library/integrations/ray.md
  integrations/sagemaker: ./library/integrations/sagemaker.md
  integrations/tensorboard: ./library/integrations/tensorboard.md
  overview/company-faq: ./overview/company-faq.md
  overview/getting-help: ./overview/getting-help.md
  overview/overview: ./overview.md
  overview/technical-faq: ./overview/technical-faq.md
  sweeps/configuration: ./library/sweeps/configuration.md
  sweeps/local: ./library/sweeps/local-controller.md
  sweeps/overview: ./library/sweeps.md
  sweeps/python: ./library/sweeps/python-api.md
  wandb/config: ./library/python/config.md
  wandb/init: ./library/python/init.md
  wandb/log: ./library/python/log.md
  wandb/restore: ./library/python/restore.md
  wandb/save: ./library/python/save.md
